version: '3.8'

services:
  app:
    build: .
    container_name: nestjs
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/market
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      REFRESH_TOKEN: ${REFRESH_TOKEN}
      PORT: 3000
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    command: >
      sh -c "npm run build && npx prisma db push && npm run start"
    networks:
      - backend

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: market
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
