version: '3.8'

services:
  app:
    build: .
    container_name: nestjs
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/market
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      REFRESH_TOKEN: ${REFRESH_TOKEN}
      PORT: 3000
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    command: >
      sh -c "npm run build && npx prisma db push && npx prisma db seed && npm run start"
    networks:
      - backend

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: market
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
